### ISSUE TITLE
Fix EventCard ComponentWillMount Warning

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/Core-v4#231]
When running tests or in the browser on `localhost:3000/events`, we see this warning:
![image](https://user-images.githubusercontent.com/36345325/72577636-58846200-3888-11ea-8d3d-2ddedfe853cb.png)

Track down the issue (it is likely the Ionicon component [here](https://github.com/SCE-Development/Core-v4/blob/44e25e174076e97f9556acd5a2323c423d856e83/src/Pages/Events/EventCard.js#L30)) 

### The solution
If it is the Ionicon component, you can do one of two things:

1. Try to update the ionicon dependency [like this](https://stackoverflow.com/questions/43127863/node-update-a-specific-package)
2. Remove the Ionicon component.

If you decide to remove Ionicon component, render the icon as an svg and store the svg in [this file](https://github.com/SCE-Development/Core-v4/blob/44e25e174076e97f9556acd5a2323c423d856e83/src/Pages/Overview/SVG.js#L3).

**Comment by arjohnston** [comment]
I recommend removing the Ionicon library as standalone SVG's are lightweight and easy to create. You can use a library like: 
https://materialdesignicons.com/
https://iconsvg.xyz/?utm_campaign=bizarrodevs&utm_medium=email&utm_source=BizarroDevs_82
https://www.svgbackgrounds.com/

a chrome extension such as: https://chrome.google.com/webstore/detail/icomoon/kppingdhhalimbaehfmhldppemnmlcjd?hl=en

Otherwise you can generate your own files through Illustrator and free alternatives and then use a compression service to compress the generated SVG files. A quick google search for online compression for SVGs is all you need

**Comment by evanugarte** [comment]
### 3/4/20
Use [this svg file](https://github.com/SCE-Development/Core-v4/blob/dev/src/Pages/Overview/SVG.js) to add the clock and map pin

**Comment by VuongAlexander** [comment]
> ### 3/4/20
> Use [this svg file](https://github.com/SCE-Development/Core-v4/blob/dev/src/Pages/Overview/SVG.js) to add the clock and map pin
> 
> Just use inspect element on the icon and copy and paste the HTML into the above file
> ![image](https://user-images.githubusercontent.com/36345325/75948463-56865a80-5e58-11ea-9e8a-6e2cdac1911a.png)

I added the HTML code of the SVG file into the SVG file above.
