### ISSUE TITLE
Creating a Yes/No component

### ISSUE THREAD

**Issue by ThaiQ** [SCE-Development/Core-v4#279]
Since we are using the YES/NO box a lot, might as well make a default version of it
Example:
![image](https://user-images.githubusercontent.com/18486562/74113099-e9342200-4b56-11ea-9dde-9596460266b1.png)

---------
To create it using hook:
1. Navigate to ```src/components``` make a folder call ```DecisionModal```
2. Navigate into ```DecisionModal``` create a file call ```DefaultDecisionModal.js```

-----------------
To initialize the hook:
1. Navigate to ```DefaultDecisionModal.js``` write the following:
```js
import React, { useState } from 'react'
export default function DefaultDecisionModal (props) {
//How to create a variable?
const [variable, setVariable] = useState("Whatever you want it to start with")

//To change variable value
setVariable("New Content")

return <div>Component Content</div>
}
```

-------------------------------------------------
Follow the first example of [reactstrap's Modal](https://reactstrap.github.io/components/modals/#app) to create your modal
**Make it look like the above image**

**Comment by evanugarte** [comment]
### 2/12 Meeting
[this file](https://github.com/SCE-Development/Core-v4/blob/9b3d4aa2eee924d09712b937d8196d8199e47fe6/src/Pages/Overview/OverviewProfile.js#L72) contains existing code that runs the modal and looks something like this:

```jsx
      <Modal isOpen={confirmationModal} toggle={toggleConfirmationModal}>
        <ModalHeader>Delete "{props.title}"?</ModalHeader>
        <ModalBody>stuff here</ModalBody>
        <ModalFooter>
          <Button onClick={toggleConfirmationModal}>Cancel</Button>
          <Button color='danger' onClick={handleDeletion}>
            Yes, delete
          </Button>
        </ModalFooter>
      </Modal>
```
What are the things we can send over as props?
1. Modal Header text
2. Modal body
3. Optional Button texts such as
```js
// render this in the buttons
const deleteText = props.deleteText || "Confirm"
const cancelText = props.cancelText || "Cancel"
```

#### How to Get this done
1. Make a file called `ConfirmationModal.js` in `src/Components`
2. Paste in the code from the above snippet
3. Refactor it to take props arguments instead of hardcoded values

Rendering your new component is like
```jsx
return (
  <ConfirmationModal headerText="header stuff" bodyText="body stuff"  {/* optional button stuff here */}/>
)
```
